apiVersion: v1
kind: ConfigMap
metadata:
  name: novaapm-backend-config
  namespace: novaapm-system
  labels:
    app.kubernetes.io/name: novaapm-backend
    app.kubernetes.io/part-of: novaapm
data:
  logs-agent-opamp-endpoint: ""
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8080
      mode: "release"
    database:
      driver: "mongodb"
      uri: ""
