apiVersion: v1
kind: Service
metadata:
  name: novaapm-frontend
  namespace: novaapm-system
  labels:
    app.kubernetes.io/name: novaapm-frontend
    app.kubernetes.io/part-of: novaapm
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: novaapm-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
